// DEL-07: deterministic, offline OpenAPI snapshot and frontend types.
import "../../apps/web/scripts/require-pinned-node.mjs";

import { spawnSync } from "node:child_process";
import { lstat, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { installNetworkGuard } from "../../scripts/node-network-guard.mjs";

export const snapshotPath = "apps/api/openapi.json";
export const typesPath = "apps/web/src/api/generated/schema.ts";
export const repositoryRoot = resolve(import.meta.dirname, "../..");

export function requireLocalReferences(value) {
  if (value === null || typeof value !== "object") return;
  for (const [key, item] of Object.entries(value)) {
    if (
      key === "$ref" &&
      (typeof item !== "string" || !item.startsWith("#/"))
    ) {
      throw new Error("OpenAPI contract contains a nonlocal reference");
    }
    requireLocalReferences(item);
  }
}

export async function renderArtifacts(
  document,
  source = JSON.stringify(document),
) {
  requireLocalReferences(document);
  if (
    document.openapi !== "3.1.0" ||
    Object.keys(document.paths ?? {}).length === 0 ||
    Object.keys(document.components?.schemas ?? {}).length === 0
  ) {
    throw new Error(
      "OpenAPI contract must contain paths and component schemas",
    );
  }
  // Install before importing the generator: even a dependency's captured Node
  // transport must be denied. JSON is passed in memory; no resolver may fetch.
  let blocked = false;
  const restore = installNetworkGuard({
    allowLoopback: false,
    onBlocked: () => {
      blocked = true;
    },
  });
  try {
    const [{ default: openapiTS, astToString }, { format }] = await Promise.all(
      [import("openapi-typescript"), import("prettier")],
    );
    const ast = await openapiTS(structuredClone(document), {
      immutable: true,
      alphabetize: true,
    });
    const header =
      "// Generated by make api-contract-generate (DEL-07). Do not edit.\n";
    const artifacts = new Map([
      [
        snapshotPath,
        // Preserve Python's numeric literals: a JS round-trip changes large
        // integer bounds to rounded decimal text in the committed snapshot.
        await format(source, { parser: "json" }),
      ],
      [
        typesPath,
        await format(header + astToString(ast), { parser: "typescript" }),
      ],
    ]);
    if (blocked) throw new Error("OpenAPI generator attempted network access");
    return artifacts;
  } finally {
    restore();
  }
}

export async function verifyOrWriteArtifacts(root, artifacts, write = false) {
  if (
    artifacts.size !== 2 ||
    !artifacts.has(snapshotPath) ||
    !artifacts.has(typesPath)
  ) {
    throw new Error("Expected exactly both API contract artifacts");
  }
  const drift = [];
  for (const [path, content] of artifacts) {
    if (![snapshotPath, typesPath].includes(path)) {
      throw new Error("Unexpected generated artifact path");
    }
    const destination = resolve(root, path);
    let parent = resolve(root);
    for (const segment of path.split("/")) {
      parent = resolve(parent, segment);
      try {
        if ((await lstat(parent)).isSymbolicLink()) {
          throw new Error(
            "Generated API artifact paths must not follow symlinks",
          );
        }
      } catch (error) {
        if (error.code !== "ENOENT") throw error;
      }
    }
    if (write) {
      await mkdir(dirname(destination), { recursive: true });
      await writeFile(destination, content, "utf8");
      continue;
    }
    let current;
    try {
      current = await readFile(destination, "utf8");
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    if (current !== content) drift.push(path);
  }
  if (drift.length !== 0) {
    throw new Error(
      `API contract drift: ${drift.join(", ")}; run make api-contract-generate`,
    );
  }
}

async function main(args) {
  let write = false;
  let python = resolve(repositoryRoot, ".venv/bin/python");
  while (args.length !== 0) {
    const arg = args.shift();
    if (arg === "--write") write = true;
    else if (arg === "--check") write = false;
    else if (arg === "--python" && args.length !== 0) python = args.shift();
    else
      throw new Error(
        "Usage: generate.mjs [--check|--write] [--python EXECUTABLE]",
      );
  }
  const result = spawnSync(python, ["-m", "scripts.export_openapi"], {
    cwd: repositoryRoot,
    encoding: "utf8",
    maxBuffer: 8 * 1024 * 1024,
    timeout: 60_000,
    env: { ...process.env, PYTHONDONTWRITEBYTECODE: "1" },
  });
  if (result.error || result.signal || result.status !== 0) {
    // Do not echo arbitrary environment-derived subprocess output in diagnostics.
    throw new Error(
      "API schema export failed; run python -m scripts.export_openapi locally",
    );
  }
  const artifacts = await renderArtifacts(
    JSON.parse(result.stdout),
    result.stdout,
  );
  await verifyOrWriteArtifacts(repositoryRoot, artifacts, write);
  process.stdout.write(
    `DEL-07 API contract ${write ? "generated" : "verified"}: ${artifacts.size} artifacts\n`,
  );
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    await main(process.argv.slice(2));
  } catch (error) {
    process.stderr.write(`${error.message}\n`);
    process.exitCode = 1;
  }
}
