"""catalog_and_deployment

Revision ID: 0001
Revises:
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_releases",
        sa.Column("content_hash", sa.String(length=96), nullable=False),
        sa.Column("content_version", sa.String(length=80), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(content_hash) = 82", name="ck_catalog_release_hash"),
        sa.CheckConstraint("length(content_version) BETWEEN 1 AND 80", name="ck_catalog_version"),
        sa.CheckConstraint("length(snapshot_json) > 2", name="ck_catalog_release_snapshot"),
        sa.PrimaryKeyConstraint("content_hash", name=op.f("pk_catalog_releases")),
        sa.UniqueConstraint("content_version", name=op.f("uq_catalog_releases_content_version")),
    )
    op.create_table(
        "local_runtime_identity",
        sa.Column("singleton_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("format_version", sa.Integer(), nullable=False),
        sa.Column("key_fingerprint", sa.String(length=90), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("format_version = 1", name="ck_local_runtime_identity_format"),
        sa.CheckConstraint(
            "length(key_fingerprint) = 90", name="ck_local_runtime_identity_fingerprint_length"
        ),
        sa.CheckConstraint("singleton_id = 1", name="ck_local_runtime_identity_singleton"),
        sa.PrimaryKeyConstraint("singleton_id", name=op.f("pk_local_runtime_identity")),
    )
    op.create_table(
        "approval_policies",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("expiry_seconds", sa.Integer(), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("release_hash", sa.String(length=96), nullable=False),
        sa.CheckConstraint(
            "kind IN ('none', 'human_external_write')", name="ck_catalog_policy_kind"
        ),
        sa.CheckConstraint("expiry_seconds BETWEEN 60 AND 86400", name="ck_catalog_policy_expiry"),
        sa.ForeignKeyConstraint(
            ["release_hash"],
            ["catalog_releases.content_hash"],
            name=op.f("fk_approval_policies_release_hash_catalog_releases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approval_policies")),
    )
    op.create_table(
        "catalog_current_release",
        sa.Column("singleton_id", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=96), nullable=False),
        sa.CheckConstraint("singleton_id = 1", name="ck_catalog_current_singleton"),
        sa.ForeignKeyConstraint(
            ["content_hash"],
            ["catalog_releases.content_hash"],
            name=op.f("fk_catalog_current_release_content_hash_catalog_releases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("singleton_id", name=op.f("pk_catalog_current_release")),
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("release_hash", sa.String(length=96), nullable=False),
        sa.CheckConstraint("display_order >= 1", name="ck_departments_display_order"),
        sa.ForeignKeyConstraint(
            ["release_hash"],
            ["catalog_releases.content_hash"],
            name=op.f("fk_departments_release_hash_catalog_releases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_departments")),
        sa.UniqueConstraint("display_order", name=op.f("uq_departments_display_order")),
    )
    op.create_table(
        "tool_capabilities",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("connector_family", sa.String(length=100), nullable=False),
        sa.Column("effect", sa.String(length=10), nullable=False),
        sa.Column("idempotency_support", sa.String(length=20), nullable=False),
        sa.Column("default_timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("release_hash", sa.String(length=96), nullable=False),
        sa.CheckConstraint("effect IN ('read', 'write')", name="ck_capability_effect"),
        sa.CheckConstraint(
            "idempotency_support IN ('not_applicable', 'required', 'supported', 'unavailable')",
            name="ck_capability_idempotency",
        ),
        sa.CheckConstraint(
            "default_timeout_seconds BETWEEN 1 AND 120", name="ck_capability_timeout"
        ),
        sa.ForeignKeyConstraint(
            ["release_hash"],
            ["catalog_releases.content_hash"],
            name=op.f("fk_tool_capabilities_release_hash_catalog_releases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_capabilities")),
    )
    op.create_table(
        "function_teams",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("department_id", sa.String(length=240), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("release_hash", sa.String(length=96), nullable=False),
        sa.CheckConstraint("display_order >= 1", name="ck_functions_display_order"),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_function_teams_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_hash"],
            ["catalog_releases.content_hash"],
            name=op.f("fk_function_teams_release_hash_catalog_releases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_function_teams")),
        sa.UniqueConstraint("department_id", "display_order", name="uq_functions_sibling_order"),
        sa.UniqueConstraint("id", "department_id", name="uq_function_department_identity"),
    )
    op.create_table(
        "agent_templates",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("department_id", sa.String(length=240), nullable=False),
        sa.Column("function_id", sa.String(length=240), nullable=False),
        sa.Column("approval_policy_id", sa.String(length=240), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("system_prompt_text", sa.Text(), nullable=False),
        sa.Column("input_schema_json", sa.Text(), nullable=False),
        sa.Column("output_schema_json", sa.Text(), nullable=False),
        sa.Column("instruction_hash", sa.String(length=64), nullable=False),
        sa.Column("input_schema_hash", sa.String(length=64), nullable=False),
        sa.Column("output_schema_hash", sa.String(length=64), nullable=False),
        sa.Column("policy_hash", sa.String(length=64), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("release_hash", sa.String(length=96), nullable=False),
        sa.CheckConstraint("display_order >= 1", name="ck_templates_display_order"),
        sa.CheckConstraint("length(input_schema_hash) = 64", name="ck_template_input_hash"),
        sa.CheckConstraint("length(instruction_hash) = 64", name="ck_template_instruction_hash"),
        sa.CheckConstraint("length(output_schema_hash) = 64", name="ck_template_output_hash"),
        sa.CheckConstraint("length(policy_hash) = 64", name="ck_template_policy_hash"),
        sa.ForeignKeyConstraint(
            ["approval_policy_id"],
            ["approval_policies.id"],
            name=op.f("fk_agent_templates_approval_policy_id_approval_policies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_agent_templates_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["function_id", "department_id"],
            ["function_teams.id", "function_teams.department_id"],
            name="fk_template_function_department",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_hash"],
            ["catalog_releases.content_hash"],
            name=op.f("fk_agent_templates_release_hash_catalog_releases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_templates")),
        sa.UniqueConstraint("function_id", "display_order", name="uq_templates_sibling_order"),
    )
    op.create_table(
        "agent_instances",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("template_id", sa.String(length=240), nullable=False),
        sa.Column("source_ordinal", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("release_hash", sa.String(length=96), nullable=False),
        sa.CheckConstraint("display_order >= 1", name="ck_instances_display_order"),
        sa.CheckConstraint("source_ordinal BETWEEN 1 AND 99", name="ck_instances_ordinal"),
        sa.ForeignKeyConstraint(
            ["release_hash"],
            ["catalog_releases.content_hash"],
            name=op.f("fk_agent_instances_release_hash_catalog_releases"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["agent_templates.id"],
            name=op.f("fk_agent_instances_template_id_agent_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_instances")),
        sa.UniqueConstraint("template_id", "display_order", name="uq_instances_sibling_order"),
        sa.UniqueConstraint("template_id", "source_ordinal", name="uq_instances_source_ordinal"),
    )
    op.create_table(
        "agent_template_capabilities",
        sa.Column("template_id", sa.String(length=240), nullable=False),
        sa.Column("capability_id", sa.String(length=240), nullable=False),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["tool_capabilities.id"],
            name=op.f("fk_agent_template_capabilities_capability_id_tool_capabilities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["agent_templates.id"],
            name=op.f("fk_agent_template_capabilities_template_id_agent_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "template_id", "capability_id", name=op.f("pk_agent_template_capabilities")
        ),
    )
    op.create_table(
        "agent_template_trigger_kinds",
        sa.Column("template_id", sa.String(length=240), nullable=False),
        sa.Column("trigger_kind", sa.String(length=12), nullable=False),
        sa.CheckConstraint(
            "trigger_kind IN ('manual', 'webhook', 'schedule')", name="ck_catalog_kind"
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["agent_templates.id"],
            name=op.f("fk_agent_template_trigger_kinds_template_id_agent_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "template_id", "trigger_kind", name=op.f("pk_agent_template_trigger_kinds")
        ),
    )
    op.create_table(
        "agent_instance_configs",
        sa.Column("instance_id", sa.String(length=240), nullable=False),
        sa.Column(
            "enabled",
            sa.Boolean(create_constraint=True, name="bool_agent_instance_configs_enabled"),
            nullable=False,
        ),
        sa.Column("variant_label", sa.String(length=100), nullable=True),
        sa.Column("trigger_bindings_json", sa.Text(), nullable=False),
        sa.Column("connector_bindings_json", sa.Text(), nullable=False),
        sa.Column("schedule_json", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("integrity_digest", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "length(connector_bindings_json) BETWEEN 2 AND 65536 AND connector_bindings_json = trim(connector_bindings_json)",
            name="ck_agent_instance_configs_connectors_bounded",
        ),
        sa.CheckConstraint(
            "length(instance_id) BETWEEN 1 AND 240 AND instance_id = trim(instance_id)",
            name="ck_agent_instance_configs_instance_id_bounded",
        ),
        sa.CheckConstraint(
            "length(integrity_digest) = 64",
            name="ck_agent_instance_configs_integrity_digest_length",
        ),
        sa.CheckConstraint(
            "length(schedule_json) BETWEEN 2 AND 65536 AND schedule_json = trim(schedule_json)",
            name="ck_agent_instance_configs_schedule_bounded",
        ),
        sa.CheckConstraint(
            "length(trigger_bindings_json) BETWEEN 2 AND 65536 AND trigger_bindings_json = trim(trigger_bindings_json)",
            name="ck_agent_instance_configs_triggers_bounded",
        ),
        sa.CheckConstraint(
            "variant_label IS NULL OR (length(variant_label) BETWEEN 1 AND 100 AND variant_label = trim(variant_label))",
            name="ck_agent_instance_configs_variant_label_bounded",
        ),
        sa.CheckConstraint("version >= 1", name="ck_agent_instance_configs_version_positive"),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["agent_instances.id"],
            name=op.f("fk_agent_instance_configs_instance_id_agent_instances"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("instance_id", name=op.f("pk_agent_instance_configs")),
    )
    op.create_table(
        "trigger_definitions",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("instance_id", sa.String(length=240), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column(
            "enabled",
            sa.Boolean(create_constraint=True, name="bool_trigger_definitions_enabled"),
            nullable=False,
        ),
        sa.Column("configuration_json", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind IN ('manual', 'webhook', 'schedule')", name="ck_trigger_kind"),
        sa.CheckConstraint(
            "length(configuration_json) BETWEEN 2 AND 65536",
            name="ck_trigger_configuration_bounded",
        ),
        sa.CheckConstraint("version >= 1", name="ck_trigger_version_positive"),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["agent_instance_configs.instance_id"],
            name=op.f("fk_trigger_definitions_instance_id_agent_instance_configs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trigger_definitions")),
        sa.UniqueConstraint("instance_id", "kind", name="uq_trigger_definitions_instance_kind"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Destructive downgrades are unsupported; restore a verified backup instead.")
