"""work_runs_steps_and_artifacts

Revision ID: 0002
Revises: 0001
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_briefs",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("revision", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("snapshot_json", sa.Text(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(objective) BETWEEN 1 AND 2000", name="ck_campaign_brief_objective"
        ),
        sa.CheckConstraint("length(snapshot_hash) = 64", name="ck_campaign_brief_snapshot_hash"),
        sa.CheckConstraint(
            "length(snapshot_json) BETWEEN 2 AND 1048576", name="ck_campaign_brief_snapshot"
        ),
        sa.CheckConstraint("length(title) BETWEEN 1 AND 200", name="ck_campaign_brief_title"),
        sa.CheckConstraint("revision >= 1", name="ck_campaign_brief_revision_positive"),
        sa.PrimaryKeyConstraint("id", "revision", name=op.f("pk_campaign_briefs")),
    )
    op.create_table(
        "work_items",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("source", sa.String(length=240), nullable=False),
        sa.Column("event_id", sa.String(length=240), nullable=False),
        sa.Column("agent_instance_id", sa.String(length=240), nullable=False),
        sa.Column("trigger_id", sa.String(length=240), nullable=False),
        sa.Column("workflow_id", sa.String(length=240), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("campaign_brief_id", sa.String(length=240), nullable=True),
        sa.Column("campaign_brief_revision", sa.Integer(), nullable=True),
        sa.Column("configuration_revision", sa.Integer(), nullable=False),
        sa.Column("admitted_payload", sa.JSON(), nullable=False),
        sa.Column("redacted_input_projection", sa.JSON(), nullable=False),
        sa.Column("input_schema_id", sa.String(length=240), nullable=False),
        sa.Column("input_schema_hash", sa.String(length=81), nullable=False),
        sa.Column("input_classification", sa.String(length=16), nullable=False),
        sa.Column("input_projection_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_projection_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("input_projection_integrity_digest", sa.String(length=64), nullable=False),
        sa.Column("input_digest", sa.String(length=64), nullable=False),
        sa.Column("admission_digest", sa.String(length=64), nullable=False),
        sa.Column("digest_key_version", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "input_classification IN ('public','internal','personal','sensitive','secret')",
            name="ck_work_items_input_classification",
        ),
        sa.CheckConstraint(
            "length(input_schema_hash) = 81 AND substr(input_schema_hash, 1, 17) = 'schema-sha256-v1:'",
            name="ck_work_items_input_schema_hash",
        ),
        sa.CheckConstraint(
            "mode IN ('dry_run', 'mock_execution')", name="ck_work_items_mode_supported"
        ),
        sa.CheckConstraint(
            "(campaign_brief_id IS NULL AND campaign_brief_revision IS NULL) OR (campaign_brief_id IS NOT NULL AND campaign_brief_revision IS NOT NULL)",
            name="ck_work_items_brief_reference_complete",
        ),
        sa.CheckConstraint(
            "campaign_brief_revision IS NULL OR campaign_brief_revision >= 1",
            name="ck_work_items_brief_revision_positive",
        ),
        sa.CheckConstraint(
            "configuration_revision >= 1", name="ck_work_items_configuration_revision_positive"
        ),
        sa.CheckConstraint(
            "input_projection_created_at = created_at AND input_projection_expires_at > input_projection_created_at",
            name="ck_work_items_input_projection_retention",
        ),
        sa.CheckConstraint(
            "length(digest_key_version) = 89", name="ck_work_items_digest_key_version_length"
        ),
        sa.CheckConstraint(
            "length(input_digest) = 64 AND length(admission_digest) = 64",
            name="ck_work_items_digest_lengths",
        ),
        sa.CheckConstraint(
            "length(input_projection_integrity_digest) = 64",
            name="ck_work_items_input_projection_integrity_digest",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_items")),
        sa.UniqueConstraint("id", "agent_instance_id", name="uq_work_items_id_instance"),
        sa.UniqueConstraint(
            "source", "event_id", "agent_instance_id", name="uq_work_items_source_event_instance"
        ),
    )
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("work_item_id", sa.String(length=240), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("catalog_hash", sa.String(length=96), nullable=False),
        sa.Column("configuration_revision", sa.Integer(), nullable=False),
        sa.Column("approval_required", sa.Boolean(), nullable=True),
        sa.Column("terminal_reason_code", sa.String(length=240), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("next_timeline_sequence", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint(
            "(state IN ('completed','failed','rejected','cancelled') AND terminal_reason_code IS NOT NULL) OR (state NOT IN ('completed','failed','rejected','cancelled') AND terminal_reason_code IS NULL)",
            name="ck_runs_terminal_reason_matches_state",
        ),
        sa.CheckConstraint(
            "(state IN ('received','validated') AND approval_required IS NULL) OR (state IN ('planned','executing','completed') AND approval_required IS NOT NULL) OR (state IN ('awaiting_approval','rejected') AND approval_required IS TRUE) OR state IN ('failed','cancelled')",
            name="ck_runs_approval_disposition_matches_state",
        ),
        sa.CheckConstraint(
            "state IN ('received','validated','planned','awaiting_approval','executing','completed','failed','rejected','cancelled')",
            name="ck_runs_state_supported",
        ),
        sa.CheckConstraint(
            "configuration_revision >= 1", name="ck_runs_configuration_revision_positive"
        ),
        sa.CheckConstraint(
            "next_timeline_sequence >= 0", name="ck_runs_timeline_sequence_nonnegative"
        ),
        sa.CheckConstraint("version >= 1", name="ck_runs_version_positive"),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("fk_runs_work_item_id_work_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runs")),
        sa.UniqueConstraint("id", "work_item_id", name="uq_runs_id_work_item"),
        sa.UniqueConstraint("work_item_id", name=op.f("uq_runs_work_item_id")),
    )
    op.create_table(
        "run_plans",
        sa.Column("run_id", sa.String(length=240), nullable=False),
        sa.Column("plan_hash", sa.String(length=64), nullable=False),
        sa.Column("workflow_id", sa.String(length=240), nullable=False),
        sa.Column("workflow_version", sa.Integer(), nullable=False),
        sa.Column("workflow_definition_hash", sa.String(length=64), nullable=False),
        sa.Column("catalog_content_hash", sa.String(length=96), nullable=False),
        sa.Column("graph_hash", sa.String(length=64), nullable=False),
        sa.Column("routing_hash", sa.String(length=64), nullable=False),
        sa.Column("approval_required", sa.Boolean(), nullable=False),
        sa.Column("step_count", sa.Integer(), nullable=False),
        sa.Column("runtime_policy_snapshot", sa.JSON(), nullable=False),
        sa.Column("runtime_policy_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(runtime_policy_hash) = 64", name="ck_run_plans_runtime_policy_hash"
        ),
        sa.CheckConstraint("step_count >= 1", name="ck_run_plans_step_count_positive"),
        sa.CheckConstraint("workflow_version >= 1", name="ck_run_plans_workflow_version"),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_plans_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_run_plans")),
        sa.UniqueConstraint("run_id", "plan_hash", name="uq_run_plans_run_hash"),
    )
    op.create_table(
        "run_state_transitions",
        sa.Column("run_id", sa.String(length=240), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("command", sa.String(length=40), nullable=False),
        sa.Column("previous_state", sa.String(length=32), nullable=True),
        sa.Column("new_state", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=240), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_version", sa.Integer(), nullable=False),
        sa.Column("resulting_version", sa.Integer(), nullable=False),
        sa.Column("completed_effect_count", sa.Integer(), nullable=False),
        sa.Column("outcome_unknown_effect_count", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(sequence = 1 AND command = 'receive' AND previous_state IS NULL AND new_state = 'received' AND expected_version = 0 AND resulting_version = 1) OR (sequence > 1 AND command <> 'receive' AND previous_state IS NOT NULL AND previous_state <> new_state)",
            name="ck_run_state_transitions_initial_or_change",
        ),
        sa.CheckConstraint(
            "command = 'cancel' OR (completed_effect_count = 0 AND outcome_unknown_effect_count = 0)",
            name="ck_run_state_transitions_effect_counts_cancel_only",
        ),
        sa.CheckConstraint(
            "command IN ('receive','mark_validated','record_plan','activate_plan','release_approved_plan','reject_approval','complete','fail','cancel')",
            name="ck_run_state_transitions_command_supported",
        ),
        sa.CheckConstraint(
            "new_state IN ('received','validated','planned','awaiting_approval','executing','completed','failed','rejected','cancelled') AND (previous_state IS NULL OR previous_state IN ('received','validated','planned','awaiting_approval','executing','completed','failed','rejected','cancelled'))",
            name="ck_run_state_transitions_states_supported",
        ),
        sa.CheckConstraint(
            "completed_effect_count >= 0 AND outcome_unknown_effect_count >= 0",
            name="ck_run_state_transitions_effect_counts_nonnegative",
        ),
        sa.CheckConstraint(
            "sequence = resulting_version AND resulting_version = expected_version + 1",
            name="ck_run_state_transitions_versions_contiguous",
        ),
        sa.CheckConstraint("sequence >= 1", name="ck_run_state_transitions_sequence_positive"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_run_state_transitions_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("run_id", "sequence", name=op.f("pk_run_state_transitions")),
    )
    op.create_table(
        "run_plan_selected_instances",
        sa.Column("run_id", sa.String(length=240), nullable=False),
        sa.Column("instance_id", sa.String(length=240), nullable=False),
        sa.Column("plan_hash", sa.String(length=64), nullable=False),
        sa.Column("template_id", sa.String(length=240), nullable=False),
        sa.Column("configuration_revision", sa.Integer(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("source_ordinal", sa.Integer(), nullable=True),
        sa.Column("selection_order", sa.Integer(), nullable=False),
        sa.Column("target", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id", "plan_hash"],
            ["run_plans.run_id", "run_plans.plan_hash"],
            name=op.f("fk_run_plan_selected_instances_run_id_run_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "run_id", "instance_id", name=op.f("pk_run_plan_selected_instances")
        ),
        sa.UniqueConstraint(
            "run_id",
            "plan_hash",
            "instance_id",
            "template_id",
            "configuration_revision",
            name="uq_plan_instances_exact_snapshot",
        ),
        sa.UniqueConstraint(
            "run_id", "plan_hash", "instance_id", "template_id", name="uq_plan_instances_template"
        ),
        sa.UniqueConstraint(
            "run_id", "plan_hash", "instance_id", name="uq_plan_instances_run_hash_id"
        ),
        sa.UniqueConstraint("run_id", "selection_order", name="uq_plan_instances_selection_order"),
    )
    op.create_table(
        "run_plan_routing_assignments",
        sa.Column("run_id", sa.String(length=240), nullable=False),
        sa.Column("slot_key", sa.String(length=240), nullable=False),
        sa.Column("plan_hash", sa.String(length=64), nullable=False),
        sa.Column("instance_id", sa.String(length=240), nullable=False),
        sa.Column("template_id", sa.String(length=240), nullable=False),
        sa.Column("required_capability_ids", sa.JSON(), nullable=False),
        sa.Column("assignment_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id", "plan_hash", "instance_id", "template_id"],
            [
                "run_plan_selected_instances.run_id",
                "run_plan_selected_instances.plan_hash",
                "run_plan_selected_instances.instance_id",
                "run_plan_selected_instances.template_id",
            ],
            name=op.f("fk_run_plan_routing_assignments_run_id_run_plan_selected_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "plan_hash"],
            ["run_plans.run_id", "run_plans.plan_hash"],
            name=op.f("fk_run_plan_routing_assignments_run_id_run_plans"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("run_id", "slot_key", name=op.f("pk_run_plan_routing_assignments")),
        sa.UniqueConstraint("run_id", "assignment_order", name="uq_plan_assignments_order"),
    )
    op.create_table(
        "run_steps",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("run_id", sa.String(length=240), nullable=False),
        sa.Column("key", sa.String(length=240), nullable=False),
        sa.Column("kind", sa.String(length=120), nullable=False),
        sa.Column("selected_instance_id", sa.String(length=240), nullable=False),
        sa.Column("capability_id", sa.String(length=240), nullable=False),
        sa.Column("effect", sa.String(length=16), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("plan_hash", sa.String(length=64), nullable=False),
        sa.Column("graph_hash", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("source_order", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.String(length=240), nullable=False),
        sa.Column("configuration_revision", sa.Integer(), nullable=False),
        sa.Column("connector_family", sa.String(length=120), nullable=False),
        sa.Column("routing_slot_key", sa.String(length=240), nullable=True),
        sa.Column("binding_id", sa.String(length=240), nullable=True),
        sa.Column("binding_configuration_revision", sa.Integer(), nullable=True),
        sa.Column("request_schema_id", sa.String(length=240), nullable=True),
        sa.Column("result_schema_id", sa.String(length=240), nullable=True),
        sa.Column("result_schema_hash", sa.String(length=81), nullable=True),
        sa.Column("request_redaction_fields", sa.JSON(), nullable=False),
        sa.Column("result_redaction_fields", sa.JSON(), nullable=False),
        sa.Column("data_classification", sa.String(length=16), nullable=False),
        sa.Column("idempotency_support", sa.String(length=32), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), nullable=True),
        sa.Column("runtime_policy_snapshot", sa.JSON(), nullable=False),
        sa.Column("runtime_policy_hash", sa.String(length=64), nullable=False),
        sa.Column("approval_policy_id", sa.String(length=240), nullable=False),
        sa.Column("approval_required_roles", sa.JSON(), nullable=False),
        sa.Column("approval_required_scopes", sa.JSON(), nullable=False),
        sa.Column("approval_expires_after_seconds", sa.Integer(), nullable=True),
        sa.Column("approval_allow_self_approval", sa.Boolean(), nullable=True),
        sa.Column("terminal_result", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("terminal_reason_code", sa.String(length=240), nullable=True),
        sa.CheckConstraint(
            "(connector_family = 'model' AND binding_id IS NULL AND binding_configuration_revision IS NULL AND timeout_seconds IS NULL AND request_schema_id IS NOT NULL AND result_schema_id IS NOT NULL AND data_classification = 'internal') OR (connector_family = 'artifact' AND binding_id IS NULL AND binding_configuration_revision IS NULL AND timeout_seconds IS NULL AND request_schema_id IS NULL AND result_schema_id IS NULL AND data_classification = 'internal') OR (connector_family NOT IN ('model','artifact') AND binding_id IS NOT NULL AND binding_configuration_revision = configuration_revision AND timeout_seconds IS NOT NULL AND request_schema_id IS NOT NULL AND result_schema_id IS NOT NULL)",
            name="ck_run_steps_binding_complete",
        ),
        sa.CheckConstraint(
            "(effect = 'read' AND idempotency_support = 'not_applicable' AND approval_expires_after_seconds IS NULL AND approval_allow_self_approval IS NULL) OR (effect = 'write' AND connector_family NOT IN ('model','artifact') AND idempotency_support = 'required' AND approval_expires_after_seconds IS NOT NULL AND approval_allow_self_approval IS NOT NULL AND request_schema_id IS NOT NULL AND result_schema_id IS NOT NULL)",
            name="ck_run_steps_effect_policy_snapshot",
        ),
        sa.CheckConstraint(
            "(result_schema_hash IS NULL AND result_schema_id IS NULL) OR (length(result_schema_hash) = 81 AND substr(result_schema_hash, 1, 17) = 'schema-sha256-v1:' AND result_schema_id IS NOT NULL)",
            name="ck_run_steps_result_schema_hash",
        ),
        sa.CheckConstraint(
            "(state IN ('succeeded','failed','rejected','cancelled','skipped') AND terminal_reason_code IS NOT NULL) OR (state NOT IN ('succeeded','failed','rejected','cancelled','skipped') AND terminal_reason_code IS NULL)",
            name="ck_run_steps_terminal_reason",
        ),
        sa.CheckConstraint(
            "data_classification IN ('public','internal','personal','sensitive','secret')",
            name="ck_run_steps_data_classification",
        ),
        sa.CheckConstraint("effect IN ('read','write')", name="ck_run_steps_effect_supported"),
        sa.CheckConstraint(
            "idempotency_support IN ('not_applicable','required','supported','unavailable')",
            name="ck_run_steps_idempotency_supported",
        ),
        sa.CheckConstraint(
            "state IN ('pending','ready','awaiting_approval','executing','succeeded','failed','rejected','cancelled','skipped')",
            name="ck_run_steps_state_supported",
        ),
        sa.CheckConstraint(
            "approval_expires_after_seconds IS NULL OR approval_expires_after_seconds >= 1",
            name="ck_run_steps_approval_expiry_positive",
        ),
        sa.CheckConstraint(
            "binding_configuration_revision IS NULL OR binding_configuration_revision >= 1",
            name="ck_run_steps_binding_config_positive",
        ),
        sa.CheckConstraint("configuration_revision >= 1", name="ck_run_steps_config_positive"),
        sa.CheckConstraint(
            "length(runtime_policy_hash) = 64", name="ck_run_steps_runtime_policy_hash"
        ),
        sa.CheckConstraint(
            "ordinal >= 1 AND source_order >= 1 AND version >= 1",
            name="ck_run_steps_positive_numbers",
        ),
        sa.CheckConstraint(
            "timeout_seconds IS NULL OR timeout_seconds BETWEEN 1 AND 120",
            name="ck_run_steps_timeout_bounded",
        ),
        sa.ForeignKeyConstraint(
            [
                "run_id",
                "plan_hash",
                "selected_instance_id",
                "template_id",
                "configuration_revision",
            ],
            [
                "run_plan_selected_instances.run_id",
                "run_plan_selected_instances.plan_hash",
                "run_plan_selected_instances.instance_id",
                "run_plan_selected_instances.template_id",
                "run_plan_selected_instances.configuration_revision",
            ],
            name=op.f("fk_run_steps_run_id_run_plan_selected_instances"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "plan_hash"],
            ["run_plans.run_id", "run_plans.plan_hash"],
            name=op.f("fk_run_steps_run_id_run_plans"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_run_steps_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run_steps")),
        sa.UniqueConstraint("id", "run_id", "key", name="uq_run_steps_id_run_key"),
        sa.UniqueConstraint("id", "run_id", name="uq_run_steps_id_run"),
        sa.UniqueConstraint("run_id", "key", name="uq_run_steps_run_key"),
        sa.UniqueConstraint("run_id", "ordinal", name="uq_run_steps_run_ordinal"),
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("work_item_id", sa.String(length=240), nullable=False),
        sa.Column("run_id", sa.String(length=240), nullable=False),
        sa.Column("step_id", sa.String(length=240), nullable=False),
        sa.Column("output_schema_id", sa.String(length=240), nullable=False),
        sa.Column("output_schema_version", sa.String(length=100), nullable=False),
        sa.Column("output_schema_hash", sa.String(length=81), nullable=False),
        sa.Column("configuration_revision", sa.Integer(), nullable=False),
        sa.Column("classification", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("provenance_snapshot", sa.JSON(), nullable=False),
        sa.Column("envelope_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "classification IN ('public','internal','personal','sensitive','secret')",
            name="ck_artifacts_classification_supported",
        ),
        sa.CheckConstraint(
            "length(output_schema_hash) = 81 AND substr(output_schema_hash, 1, 17) = 'schema-sha256-v1:'",
            name="ck_artifacts_output_schema_hash",
        ),
        sa.CheckConstraint(
            "configuration_revision >= 1", name="ck_artifacts_configuration_revision_positive"
        ),
        sa.CheckConstraint(
            "length(payload_hash) = 64 AND length(envelope_fingerprint) = 64",
            name="ck_artifacts_digest_lengths",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["runs.id"], name=op.f("fk_artifacts_run_id_runs"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["step_id", "run_id"],
            ["run_steps.id", "run_steps.run_id"],
            name=op.f("fk_artifacts_step_id_run_steps"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("fk_artifacts_work_item_id_work_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint("id", "run_id", "step_id", name="uq_artifacts_id_run_step"),
    )
    op.create_table(
        "run_step_dependencies",
        sa.Column("step_id", sa.String(length=240), nullable=False),
        sa.Column("dependency_key", sa.String(length=240), nullable=False),
        sa.Column("run_id", sa.String(length=240), nullable=False),
        sa.Column("step_key", sa.String(length=240), nullable=False),
        sa.CheckConstraint("step_key <> dependency_key", name="ck_step_dependencies_not_self"),
        sa.ForeignKeyConstraint(
            ["run_id", "dependency_key"],
            ["run_steps.run_id", "run_steps.key"],
            name=op.f("fk_run_step_dependencies_run_id_run_steps"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["step_id", "run_id", "step_key"],
            ["run_steps.id", "run_steps.run_id", "run_steps.key"],
            name=op.f("fk_run_step_dependencies_step_id_run_steps"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("step_id", "dependency_key", name=op.f("pk_run_step_dependencies")),
    )
    op.create_table(
        "run_step_state_transitions",
        sa.Column("step_id", sa.String(length=240), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.String(length=240), nullable=False),
        sa.Column("command", sa.String(length=40), nullable=False),
        sa.Column("previous_state", sa.String(length=32), nullable=True),
        sa.Column("new_state", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=240), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expected_version", sa.Integer(), nullable=False),
        sa.Column("resulting_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(sequence = 1 AND command = 'initialize' AND previous_state IS NULL AND new_state = 'pending' AND expected_version = 0 AND resulting_version = 1) OR (sequence > 1 AND command <> 'initialize' AND previous_state IS NOT NULL AND previous_state <> new_state)",
            name="ck_step_transitions_initial_or_change",
        ),
        sa.CheckConstraint(
            "command IN ('initialize','mark_ready','wait_for_approval','release_approval','start_reserved_write','start','succeed','fail','reject','cancel','skip')",
            name="ck_step_transitions_command_supported",
        ),
        sa.CheckConstraint(
            "new_state IN ('pending','ready','awaiting_approval','executing','succeeded','failed','rejected','cancelled','skipped') AND (previous_state IS NULL OR previous_state IN ('pending','ready','awaiting_approval','executing','succeeded','failed','rejected','cancelled','skipped'))",
            name="ck_step_transitions_states_supported",
        ),
        sa.CheckConstraint(
            "sequence = resulting_version AND resulting_version = expected_version + 1",
            name="ck_step_transitions_versions_contiguous",
        ),
        sa.CheckConstraint("sequence >= 1", name="ck_step_transitions_sequence_positive"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_run_step_state_transitions_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["step_id", "run_id"],
            ["run_steps.id", "run_steps.run_id"],
            name=op.f("fk_run_step_state_transitions_step_id_run_steps"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("step_id", "sequence", name=op.f("pk_run_step_state_transitions")),
        sa.UniqueConstraint(
            "step_id", "run_id", "sequence", name="uq_step_transitions_step_run_sequence"
        ),
    )
    op.create_table(
        "artifact_parent_edges",
        sa.Column("artifact_id", sa.String(length=240), nullable=False),
        sa.Column("parent_artifact_id", sa.String(length=240), nullable=False),
        sa.Column("run_id", sa.String(length=240), nullable=False),
        sa.Column("artifact_step_id", sa.String(length=240), nullable=False),
        sa.Column("parent_step_id", sa.String(length=240), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "artifact_id <> parent_artifact_id", name="ck_artifact_parent_edges_not_self"
        ),
        sa.CheckConstraint("ordinal >= 1", name="ck_artifact_parent_edges_ordinal_positive"),
        sa.ForeignKeyConstraint(
            ["artifact_id", "run_id", "artifact_step_id"],
            ["artifacts.id", "artifacts.run_id", "artifacts.step_id"],
            name=op.f("fk_artifact_parent_edges_artifact_id_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_artifact_id", "run_id", "parent_step_id"],
            ["artifacts.id", "artifacts.run_id", "artifacts.step_id"],
            name=op.f("fk_artifact_parent_edges_parent_artifact_id_artifacts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "artifact_id", "parent_artifact_id", name=op.f("pk_artifact_parent_edges")
        ),
        sa.UniqueConstraint(
            "artifact_id", "ordinal", name="uq_artifact_parent_edges_artifact_ordinal"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Destructive downgrades are unsupported; restore a verified backup instead.")
