"""webhooks_schedules_and_occurrences

Revision ID: 0004
Revises: 0003
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedules",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("trigger_id", sa.String(length=240), nullable=False),
        sa.Column("instance_id", sa.String(length=240), nullable=False),
        sa.Column("workflow_id", sa.String(length=240), nullable=False),
        sa.Column("cron_expression", sa.String(length=100), nullable=False),
        sa.Column("timezone_name", sa.String(length=100), nullable=False),
        sa.Column("recurrence_version", sa.String(length=64), nullable=False),
        sa.Column("next_run_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_scheduled_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("misfire_policy", sa.String(length=16), nullable=False),
        sa.Column("misfire_grace_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "enabled",
            sa.Boolean(create_constraint=True, name="bool_schedules_enabled"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=240), nullable=True),
        sa.Column("lease_claimed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_expires_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("integrity_digest", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "misfire_policy IN ('skip','run_once')", name="ck_schedules_misfire_policy_supported"
        ),
        sa.CheckConstraint(
            "(lease_owner IS NULL AND lease_claimed_at_utc IS NULL AND lease_expires_at_utc IS NULL) OR (lease_owner IS NOT NULL AND lease_claimed_at_utc IS NOT NULL AND lease_expires_at_utc IS NOT NULL)",
            name="ck_schedules_lease_complete",
        ),
        sa.CheckConstraint(
            "last_scheduled_at_utc IS NULL OR last_scheduled_at_utc < next_run_at_utc",
            name="ck_schedules_last_precedes_next",
        ),
        sa.CheckConstraint(
            "lease_claimed_at_utc IS NULL OR next_run_at_utc <= lease_claimed_at_utc",
            name="ck_schedules_lease_due_at_claim",
        ),
        sa.CheckConstraint(
            "lease_expires_at_utc IS NULL OR lease_expires_at_utc > lease_claimed_at_utc",
            name="ck_schedules_lease_expiry_after_claim",
        ),
        sa.CheckConstraint(
            "lease_owner IS NULL OR (length(lease_owner) BETWEEN 1 AND 240 AND lease_owner = trim(lease_owner))",
            name="ck_schedules_lease_owner_bounded",
        ),
        sa.CheckConstraint(
            "lease_owner IS NULL OR version >= 2", name="ck_schedules_lease_version_advanced"
        ),
        sa.CheckConstraint(
            "length(cron_expression) BETWEEN 1 AND 100 AND cron_expression = trim(cron_expression)",
            name="ck_schedules_cron_bounded",
        ),
        sa.CheckConstraint(
            "length(integrity_digest) = 64", name="ck_schedules_integrity_digest_length"
        ),
        sa.CheckConstraint(
            "length(recurrence_version) BETWEEN 1 AND 64 AND recurrence_version = trim(recurrence_version)",
            name="ck_schedules_recurrence_version_bounded",
        ),
        sa.CheckConstraint(
            "length(timezone_name) BETWEEN 1 AND 100 AND timezone_name = trim(timezone_name)",
            name="ck_schedules_timezone_bounded",
        ),
        sa.CheckConstraint(
            "misfire_grace_seconds BETWEEN 0 AND 86400 AND misfire_grace_seconds = CAST(misfire_grace_seconds AS INTEGER)",
            name="ck_schedules_misfire_grace_bounded",
        ),
        sa.CheckConstraint("version >= 1", name="ck_schedules_version_positive"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
    )
    op.create_table(
        "webhook_receipts",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("source", sa.String(length=240), nullable=False),
        sa.Column("event_id", sa.String(length=240), nullable=False),
        sa.Column("trigger_id", sa.String(length=240), nullable=False),
        sa.Column("body_digest", sa.String(length=64), nullable=False),
        sa.Column("digest_key_version", sa.String(length=128), nullable=False),
        sa.Column("mapper_version", sa.String(length=240), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(digest_key_version) = 92 AND substr(digest_key_version, 1, 28) = 'webhook-body-hmac-sha256-v1:'",
            name="ck_webhook_receipts_digest_key_version",
        ),
        sa.CheckConstraint(
            "length(body_digest) = 64 AND body_digest = lower(body_digest)",
            name="ck_webhook_receipts_body_digest",
        ),
        sa.CheckConstraint(
            "length(event_id) BETWEEN 1 AND 240 AND event_id = trim(event_id)",
            name="ck_webhook_receipts_event_id_bounded",
        ),
        sa.CheckConstraint(
            "length(id) BETWEEN 1 AND 240 AND id = trim(id)", name="ck_webhook_receipts_id_bounded"
        ),
        sa.CheckConstraint(
            "length(mapper_version) BETWEEN 1 AND 240 AND mapper_version = trim(mapper_version)",
            name="ck_webhook_receipts_mapper_version_bounded",
        ),
        sa.CheckConstraint(
            "length(source) BETWEEN 1 AND 240 AND source = trim(source)",
            name="ck_webhook_receipts_source_bounded",
        ),
        sa.CheckConstraint(
            "length(trigger_id) BETWEEN 1 AND 240 AND trigger_id = trim(trigger_id)",
            name="ck_webhook_receipts_trigger_id_bounded",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_receipts")),
        sa.UniqueConstraint("source", "event_id", name="uq_webhook_receipts_source_event"),
    )
    op.create_table(
        "schedule_occurrences",
        sa.Column("id", sa.String(length=240), nullable=False),
        sa.Column("identity_scheme", sa.String(length=64), nullable=False),
        sa.Column("schedule_id", sa.String(length=240), nullable=False),
        sa.Column("scheduled_for_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_local", sa.String(length=32), nullable=False),
        sa.Column("timezone_name", sa.String(length=100), nullable=False),
        sa.Column("timezone_fold", sa.Integer(), nullable=False),
        sa.Column("recurrence_version", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("misfire_policy_applied", sa.String(length=16), nullable=True),
        sa.Column("misfire_grace_seconds", sa.Integer(), nullable=True),
        sa.Column("misfire_evaluated_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_missed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_missed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("missed_count", sa.Integer(), nullable=True),
        sa.Column("work_item_id", sa.String(length=240), nullable=True),
        sa.Column("run_id", sa.String(length=240), nullable=True),
        sa.Column("integrity_digest", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "(misfire_policy_applied IS NULL AND state IN ('due','claimed','enqueued','completed')) OR (misfire_policy_applied IS NOT NULL AND ((misfire_policy_applied = 'skip' AND state = 'skipped') OR (misfire_policy_applied = 'run_once' AND state IN ('claimed','enqueued','completed'))))",
            name="ck_schedule_occurrences_misfire_state",
        ),
        sa.CheckConstraint(
            "(state IN ('enqueued','completed') AND work_item_id IS NOT NULL) OR (state IN ('due','claimed','skipped') AND work_item_id IS NULL)",
            name="ck_schedule_occurrences_state_receipt",
        ),
        sa.CheckConstraint(
            "misfire_policy_applied IS NULL OR misfire_policy_applied IN ('skip','run_once')",
            name="ck_schedule_occurrences_misfire_policy_supported",
        ),
        sa.CheckConstraint(
            "state IN ('due','claimed','enqueued','skipped','completed')",
            name="ck_schedule_occurrences_state_supported",
        ),
        sa.CheckConstraint(
            "(misfire_policy_applied IS NULL AND misfire_grace_seconds IS NULL AND misfire_evaluated_at_utc IS NULL AND first_missed_at_utc IS NULL AND last_missed_at_utc IS NULL AND missed_count IS NULL) OR (misfire_policy_applied IS NOT NULL AND misfire_grace_seconds IS NOT NULL AND misfire_evaluated_at_utc IS NOT NULL AND first_missed_at_utc IS NOT NULL AND last_missed_at_utc IS NOT NULL AND missed_count IS NOT NULL)",
            name="ck_schedule_occurrences_misfire_complete",
        ),
        sa.CheckConstraint(
            "(work_item_id IS NULL AND run_id IS NULL) OR (work_item_id IS NOT NULL AND run_id IS NOT NULL)",
            name="ck_schedule_occurrences_receipt_complete",
        ),
        sa.CheckConstraint(
            "first_missed_at_utc IS NULL OR (first_missed_at_utc = scheduled_for_utc AND first_missed_at_utc <= last_missed_at_utc AND last_missed_at_utc <= misfire_evaluated_at_utc)",
            name="ck_schedule_occurrences_missed_range",
        ),
        sa.CheckConstraint(
            "length(identity_scheme) BETWEEN 1 AND 64 AND identity_scheme = trim(identity_scheme)",
            name="ck_schedule_occurrences_identity_scheme_bounded",
        ),
        sa.CheckConstraint(
            "length(integrity_digest) = 64", name="ck_schedule_occurrences_integrity_digest_length"
        ),
        sa.CheckConstraint(
            "length(recurrence_version) BETWEEN 1 AND 64 AND recurrence_version = trim(recurrence_version)",
            name="ck_schedule_occurrences_recurrence_version_bounded",
        ),
        sa.CheckConstraint(
            "length(scheduled_local) = 26", name="ck_schedule_occurrences_local_canonical_length"
        ),
        sa.CheckConstraint(
            "length(timezone_name) BETWEEN 1 AND 100 AND timezone_name = trim(timezone_name)",
            name="ck_schedule_occurrences_timezone_bounded",
        ),
        sa.CheckConstraint(
            "misfire_grace_seconds IS NULL OR (misfire_grace_seconds BETWEEN 0 AND 86400 AND misfire_grace_seconds = CAST(misfire_grace_seconds AS INTEGER))",
            name="ck_schedule_occurrences_misfire_grace_bounded",
        ),
        sa.CheckConstraint(
            "missed_count IS NULL OR (missed_count BETWEEN 1 AND 10000 AND missed_count = CAST(missed_count AS INTEGER) AND ((missed_count = 1 AND last_missed_at_utc = first_missed_at_utc) OR (missed_count > 1 AND last_missed_at_utc > first_missed_at_utc)))",
            name="ck_schedule_occurrences_missed_count",
        ),
        sa.CheckConstraint("timezone_fold IN (0,1)", name="ck_schedule_occurrences_fold_supported"),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("fk_schedule_occurrences_run_id_runs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
            name=op.f("fk_schedule_occurrences_schedule_id_schedules"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("fk_schedule_occurrences_work_item_id_work_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_occurrences")),
        sa.UniqueConstraint("id", "schedule_id", name="uq_schedule_occurrences_id_schedule"),
        sa.UniqueConstraint("run_id", name="uq_schedule_occurrences_run"),
        sa.UniqueConstraint(
            "schedule_id", "scheduled_for_utc", name="uq_schedule_occurrences_schedule_due"
        ),
        sa.UniqueConstraint("work_item_id", name="uq_schedule_occurrences_work_item"),
    )
    op.create_table(
        "webhook_receipt_deliveries",
        sa.Column("receipt_id", sa.String(length=240), nullable=False),
        sa.Column("instance_id", sa.String(length=240), nullable=False),
        sa.Column("work_item_id", sa.String(length=240), nullable=False),
        sa.Column("run_id", sa.String(length=240), nullable=False),
        sa.CheckConstraint(
            "length(instance_id) BETWEEN 1 AND 240 AND instance_id = trim(instance_id)",
            name="ck_webhook_receipt_deliveries_instance_id_bounded",
        ),
        sa.CheckConstraint(
            "length(receipt_id) BETWEEN 1 AND 240 AND receipt_id = trim(receipt_id)",
            name="ck_webhook_receipt_deliveries_receipt_id_bounded",
        ),
        sa.CheckConstraint(
            "length(run_id) BETWEEN 1 AND 240 AND run_id = trim(run_id)",
            name="ck_webhook_receipt_deliveries_run_id_bounded",
        ),
        sa.CheckConstraint(
            "length(work_item_id) BETWEEN 1 AND 240 AND work_item_id = trim(work_item_id)",
            name="ck_webhook_receipt_deliveries_work_item_id_bounded",
        ),
        sa.ForeignKeyConstraint(
            ["instance_id"],
            ["agent_instance_configs.instance_id"],
            name=op.f("fk_webhook_receipt_deliveries_instance_id_agent_instance_configs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["webhook_receipts.id"],
            name=op.f("fk_webhook_receipt_deliveries_receipt_id_webhook_receipts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "work_item_id"],
            ["runs.id", "runs.work_item_id"],
            name="fk_webhook_receipt_deliveries_run_work",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id", "instance_id"],
            ["work_items.id", "work_items.agent_instance_id"],
            name="fk_webhook_receipt_deliveries_work_instance",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "receipt_id", "instance_id", name=op.f("pk_webhook_receipt_deliveries")
        ),
        sa.UniqueConstraint("run_id", name="uq_webhook_receipt_deliveries_run"),
        sa.UniqueConstraint("work_item_id", name="uq_webhook_receipt_deliveries_work_item"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError("Destructive downgrades are unsupported; restore a verified backup instead.")
